#!/usr/bin/env bash
#type of network a computer in local is connected
#type of network could connect an office in one building to another office in a building a few streets away
#What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)

3
2
1
