#!/usr/bin/env bash
#displays numbers from 1 to 20 

i=1

while [ $i -le 20 ]
do 
 echo "$i"
case $i in 
	"4") echo "bad luck from china";;
 	"9") echo "bad luck in japan";;
	"17") echo "bad luck in italy";;
esac
(( i++ ))
done


